### ISSUE TITLE
appendBitmap on Android does not resolve images from the Web

### ISSUE THREAD

**Issue by dnlowman** [infoxicator/react-native-star-prnt#18]
The iOS implementation allows the resolution of images from the web however the android implementation does not, should we update the android implementation to support both resolving images from the web?

**Comment by infoxicator** [comment]
Hi @dnlowman not sure exactly what you refer to but I think one of the contributors fixed a problem with scaling on iOS, look at this [commit](https://github.com/infoxicator/react-native-star-prnt/pull/8/commits/36e7c07d386f375633740f0d85010419be6d7154). Maybe is also happening on android? is this to do with the appendBitmap command?

**Comment by infoxicator** [comment]
Hi @dnlowman, It looks like the iOS implementation creates an image regardless of the url (local or remote) 
`      NSURL *imageURL = [NSURL URLWithString:urlString];
            NSData *imageData = [NSData dataWithContentsOfURL:imageURL];
            UIImage *image = [UIImage imageWithData:imageData];`

whereas the android implementation explicitly loads an image from the phone's memory:
```
Uri imageUri =  Uri.parse(uriString);
 Bitmap bitmap = MediaStore.Images.Media.getBitmap(contentResolver, imageUri);
```

The purpose of this command was always intended to be printing from the phone's memory not remote. One solution is to download your image and then pass it to appendBitmap function so it works on both platforms. 

An alternative is maybe investigate if Java android allows you to pass a remote url to create a bitmap. The problem is to decide when is a remote image and when is a local one.
